[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2018"

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
blake3 = { version = "0.1", features = ["c_avx512"] }
once_cell = "1.4"

# Local patches - typically git references
[patch.crates-io]
